### ISSUE TITLE
Interpreting percentage output in pprof output

### ISSUE THREAD

**Issue by kuriwaki** [r-prof/proffer#25]
## Question

I relatively new to profiling, so I'd appreciate how to interpret the numbers in the pprof plot. 

For example, I get this component running proffer:
<img width="188" alt="image" src="https://user-images.githubusercontent.com/8290417/85775971-44be1100-b6ee-11ea-88d0-6cb9b0de7c34.png">

- What do each of the four numbers mean? Can I interpret 4.52% as "`data.frame()` took  up 4.52% of the total time spent running my command"?
- What does the size of the box represent? I first thought it represented the amount of time it took, but in my image, a box that says `0 of 21 (8.82%)`  is smaller than the above box, which is only 4.52%.
- It seems like the pprofer is representing `data.frame` as `data_frame()`. Since these are actually different in R, it would be nice if we could differentiate.

**Comment by wlandau** [comment]
This is exactly why I prefer the flame graphs instead of the graphs with those boxes. You can select the type of display in the menu on the upper left.

I do not remember exactly what those counts and percentages mean in the boxes, nor the exact meaning of the box size, but there are analogous statistics in the "Top" view, and the meanings of the entries in the table are better documented (e.g. [here](https://stackoverflow.com/questions/32571396/pprof-and-golang-how-to-interpret-a-results)).

`proffer` is just an R wrapper around R's existing profiler and [Google `pprof`](https://github.com/google/pprof), so unfortunately there is no way to stop `data.frame` from becoming `data_frame` through `proffer`.
