### ISSUE TITLE
Save as html 

### ISSUE THREAD

**Issue by liutiming** [r-prof/proffer#29]
I am using proffer via vscode remote ssh on a cluster and for some reason even if I set browser to FALSE and set a port (like 10010), vscode does not forward the port for me (page loading but no content). 

If we can save it to a html, then I'll be able to use add on like vscode preview server to view it on my local browser. The add on will auto reload whenever there's a change to the file, too.  

Is it possible to do that? Thanks!

**Comment by wlandau** [comment]
> I am using proffer via vscode remote ssh on a cluster and for some reason even if I set browser to FALSE and set a port (like 10010), vscode does not forward the port for me (page loading but no content).

This requires setting `host = "0.0.0.0"` in `pprof()` so the server can accept connections from anywhere on the local network.

> If we can save it to a html, then I'll be able to use add on like vscode preview server to view it on my local browser. The add on will auto reload whenever there's a change to the file, too.

As a workaround, you can generate the [`pprof`](https://github.com/google/pprof) samples protocol buffer yourself with `proffer::record_pprof()`, then call `pprof -web your_samples.proto` in the shell to generate an svg. I have no plans to wrap an R interface around this part because Google  [`pprof`](https://github.com/google/pprof) supports many kinds of graph, I have had to work through unexpected breaking changes in past versions of the `pprof` command line interface, and the `pprof` maintainers are [deliberately avoiding formal releases](https://github.com/google/pprof/issues/364). I do not think trying to build an R interface to all of `pprof` would be very robust or add much value.

**Comment by wlandau** [comment]
For reference: https://r-prof.github.io/proffer/#serving-pprof-remotely
