### ISSUE TITLE
Profiling packages and reproducible scripts

### ISSUE THREAD

**Issue by Robinlovelace** [r-prof/proffer#4]
## Prework

- [x] Read and abide by `proffer`'s [code of conduct](https://github.com/r-prof/proffer/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/r-prof/proffer/issues), both open and closed.
- [x] If you think your question has a quick and definite answer, consider posting to [Stack Overflow](https://stackoverflow.com) under the [`proffer-r-package` tag](https://stackoverflow.com/tags/proffer-r-package). (If you anticipate extended follow-up and discussion, you are already in the right place!)

## Question

What would you like to know?

This is really 2 questions but I think they're related so asking in one.

Will the package be able to profile scripts and packages? Sometimes when developing a package the build time is slow and it's not always clear which vignette, example or function is responsible. Would be great to have flame graphs for package build processes and arbitrary reproducible scripts (e.g. an extension to `reprex` that allows it to create a flamegraph of the code just reproduced could be awesome and useful).

**Comment by wlandau** [comment]
> Will the package be able to profile scripts and packages?

You could profile scripts with `pprof(source("script.R"))` and individual package functions with something like `pprof(package::function())`. In the latter, case, `pprof()` will not pick up low-level compiled code automatically, and I would recommend getting a `pprof` file with [`jointprof`](https://github.com/r-prof/jointprof) and then supplying it to `proffer::serve_pprof()`.

> Sometimes when developing a package the build time is slow and it's not always clear which vignette, example or function is responsible.

`proffer` uses `Rprof()` in the backend and then converts the profiling output to `pprof` format. Because of how that works, `proffer` does not see processes outside your current session, including package build processes. The following flame graph is the output from `pprof(devtools::build("proffer"))`, all it's showing is that most of the time is spent on a child process (e.g. `callr::rcmd_safe()`)

![Screen Shot 2019-12-12 at 8 24 57 AM](https://user-images.githubusercontent.com/1580860/70715848-22682700-1cb9-11ea-88d0-a9e8601f4c59.png)

But if there is an unusually long vignette and you know it is the bottleneck, you can call `pprof(rmarkdown::render("vignette.Rmd"))` to find out why the vignette is slow.

Other profiling software such as [`gperftools`](https://github.com/gperftools/gperftools) can generate profiling data from command line programs. You may be able to use it with `R CMD build`, convert the profiling data to `pprof` format (see `proffer::to_pprof()` and `profile::write_pprof()`) and supply the `pprof` file to `proffer::serve_pprof()`.

**Comment by Robinlovelace** [comment]
Thanks for the quick and useful response @wlandau. May be of use in a 2nd edition of Efficient R Programming - heads-up @csgillespie. Lots of things in the benchmarking/profiling space have evolved since 2015 when we wrote the bulk of the book and by the looks of it this is on that will make profiling easier. Will keep my eye on future developments.

**Comment by wlandau** [comment]
That's exciting. I encourage you to reach out to @krlmlr for this. He has done far more work in this area, including an [R Consortium project](https://www.r-consortium.org/projects/awarded-projects).  He wrote the [`profile`](https://github.com/r-prof/profile) package, which can convert `Rprof()` files to `pprof` format, and he wrote the [`jointprof`](https://github.com/r-prof/jointprof) package, which jointly profiles R code with low-level compiled code. Without `profile`, `proffer` would not exist.

**Comment by Robinlovelace** [comment]
Great thanks for the heads-up. Had a good chat with Kirill at UseR 2019 and keen to collaborate. Consider us linked-up!
